### ISSUE TITLE
conda commands

### ISSUE THREAD

**Issue by maguileraf** [widdowquinn/find_differential_primers#54] opened 2020-11-30 16:26 UTC
I installed find_differential_primers with conda install -c bioconda find_differential_primers but after installation it says that pdp command is not found. Are there different commands besides the one on pdp documentation?

**Comment by widdowquinn** [comment] 2020-11-30 17:53
Hi @maguileraf 

Thank you for your interest in `pdp`.

This is a duplicate of #48 #49 - the `conda` package installs `find_differential_primers.py`. `pdp` is the current development version. To install it, please clone the repository and use `python setup.py install`.

L.

**Closed as completed by widdowquinn** 2020-11-30 17:53 UTC
Labels: question

**Comment by nick-youngblut** [comment] 2020-12-17 15:38
Given the number of duplicate issues, it seems that a lot of users hit this problem (I just did). Given that I don't want to install of the dependencies separately, I did the following:

```
conda create -n primers find_differential_primers
conda activate primers
git clone git@github.com:widdowquinn/find_differential_primers.git
cd find_differential_primers
python setup.py install
```

...but that seems to have caused conflicts between find_differential_primers & pdp: 

```
$ pdp config -h
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/primers/bin/pdp", line 33, in <module>
    sys.exit(load_entry_point('diagnostic-primers==0.2.0.dev0', 'console_scripts', 'pdp')())
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/primers/bin/pdp", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/primers/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/primers/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/primers/lib/python3.8/site-packages/diagnostic_primers-0.2.0.dev0-py3.8.egg/diagnostic_primers/scripts/pdp_script.py", line 48, in <module>
ImportError: cannot import name 'parsers' from 'diagnostic_primers.scripts' (/ebio/abt3_projects/software/dev/miniconda3_dev/envs/primers/lib/python3.8/site-packages/diagnostic_primers-0.2.0.dev0-py3.8.egg/diagnostic_primers/scripts/__init__.py)
```

It would be helpful to point people to your [.travis.yml](https://github.com/widdowquinn/find_differential_primers/blob/diagnostic_primers/.travis.yml), which shows how you create an env for running pdp.

For those that want to integrate `pdp` into a snakemake pipeline, it would be really helpful to have an update bioconda recipe. 

Using `mamba` should substantially speed up your CI setup.

**Comment by widdowquinn** [comment] 2020-12-17 18:37
Hi Nick,

Thanks for the note, I'll look into `mamba`.

I don't think `pdp` is ready for public consumption yet - it's still very much in alpha. I don't really want to put it up on `conda` until it's more usable. `find_differential_primers.py` is at least stable. I don't really want to restore `master` as the base view on GitHub, but I'm tempted, to avoid the confusion. Also, please be aware that `pdp` subcommands might not do exactly what's advertised, at the moment.

You are bound to run into problems trying to install `pdp` and `find_differential_primers.py` in the same environment, unfortunately - they're not meant to play nice together. I'd suggest installing them into separate environments to avoid cross-talk.

L.
